name: Deploy Application

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main
  pull_request:
    branches:
      - main  # Runs on PRs to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (or any other environment)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Replace with relevant test command

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Deploying..."
          # Add deployment script here (e.g., SSH into a server, push to a cloud service, etc.)
